### ISSUE TITLE
RODec中无监督训练是矩阵2范数还是F范数呢

### ISSUE THREAD

**Issue by qianchne** [shangqigao/RONet#1]
祝贺大佬喜提TPAMI，研一小白前来学习。
在您的论文中，无监督的RODec训练是利用矩阵的二范数。
但是在RODec_model.py中：
        if self.mode == 'unsupervised':
            RODec_loss = tf.reduce_mean(tf.square(output_batch[2]))
这好像是约束了矩阵的F范数。
谢谢您的指点。

**Comment by shangqigao** [comment]
我们用的是向量的2范数，也就是矩阵或者张量的F范数。关于范数的使用在3.1节的前一段(Table 1 ....)有申明，可以参考。
